spring:
  application:
    name: AdlasApp
  datasource:
    url: jdbc:mysql://localhost:3306/avs
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sa
    password: pass@123
  jpa:
    database-platform:  org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8088
  servlet:
    context-path: /adlasapp

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs-ui
#    operations-sorter: method
#    tags-sorter: alpha
#  writer-with-order-by-keys: true